server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: container-logs
      __path__: /logs/**/current.log
  pipeline_stages:
    - match:
        selector: '{job="container-logs"}'
        stages:
        - regex:
            source: filename
            expression: "/logs/.+/namespaces/(?P<namespace>.+?)/pods/(?P<pod>.+?)/(?P<container>.+?)/(?P<container2>.+?)/logs/.*"
        - cri: {}
        - regex:
            expression: "^(?s)(?P<time>\\S+?) (?P<message>.*)$"
        - timestamp:
            source: time
            format: RFC3339Nano
        - output:
            source: message
        - labels:
            namespace:
            pod:
            container:
